
name: Check compile

on:
  push

jobs:
  with-darwin:
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v12
    - run: nix-build -A bazel-watcher --keep-failed
    - run: sudo find / -iname 'libarclite*'
      if: failure()
    - run: sudo tar -cvf ${{ github.workspace }}/build.tar nix-build-*
      if: failure()
      working-directory: /private/tmp
    - uses: actions/upload-artifact@v2
      if: failure()
      with:
        path: build.tar

  #on-linux:
  #  runs-on: ubuntu-latest
  #  steps:
  #  - uses: actions/checkout@v2.3.4
  #  - uses: cachix/install-nix-action@v12
  #  - run: nix-build -A bazel-watcher --keep-failed
  #  - run: sudo tar -cvf ${{ github.workspace }}/build.tar nix-build-*
  #    if: failure()
  #    working-directory: /private/tmp
  #  - uses: actions/upload-artifact@v2
  #    if: failure()
  #    with:
  #      path: build.tar
