
name: Check compile

on:
  push

jobs:
  with-darwin:
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v12
    - run: nix-build -A libmodplug --keep-failed
    - uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: nix-build
        path: /private/tmp/nix-build-libmodplug-*

